import type { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local";

const mainFont = localfont({
  src: "../public/font/noto.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mainFont.className}>{children}</body>
    </html>
  );
}
