import type { Metadata } from "next";
import "./globals.css";
import localfont from "next/font/local";
import { auth } from "@/auth";
import { AuthProvider } from "@/context/auth-context";
const mainFont = localfont({
  src: "../public/font/noto.ttf",
});
import { SessionProvider } from "next-auth/react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessions = await auth();
  return (
    <SessionProvider session={sessions}>
      <html lang="en">
        <body className={mainFont.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
